from .models import Case, Conversation, Customer, Policy, Scenario, Transaction

SCENARIOS = [
    Scenario("refund-standard", "Standard refund", "Verified customer, low value transaction.", "CONTINUE"),
    Scenario("refund-approval", "Large refund", "Refund exceeds the automatic policy limit.", "APPROVAL"),
    Scenario("fraud-handoff", "Suspected fraud", "Risk signal requires a specialist.", "HANDOFF"),
    Scenario("missing-context", "Missing context", "Insufficient information to safely proceed.", "CLARIFY"),
    Scenario("duplicate-charge", "Duplicate charge", "Two settled charges require payment investigation.", "HANDOFF"),
    Scenario("refund-missing", "Refund not received", "A promised refund is not visible in the payment record.", "HANDOFF"),
    Scenario("policy-exception", "Policy exception", "A request falls outside standard refund policy.", "APPROVAL"),
    Scenario("status-lookup", "Payment status", "A routine payment status lookup.", "CONTINUE"),
    Scenario("account-action", "Account action", "A sensitive account action needs supervisor authority.", "APPROVAL"),
    Scenario("conflicting-records", "Conflicting records", "Payment systems disagree about the transaction state.", "HANDOFF"),
]
CUSTOMERS = [
    Customer("cus-100", "Asha Rao", "standard"),
    Customer("cus-200", "Mateo Silva", "premium"),
    Customer("cus-300", "Noor Khan", "standard", verified=False),
    Customer("cus-401", "Inez Martin", "standard"),
    Customer("cus-402", "Jon Bell", "premium"),
    Customer("cus-403", "Priya Nair", "standard"),
    Customer("cus-404", "Owen Brooks", "business"),
    Customer("cus-405", "Lina Chen", "premium"),
    Customer("cus-406", "Samir Patel", "standard"),
    Customer("cus-407", "Elena Rossi", "standard"),
    Customer("cus-408", "Theo Grant", "business"),
    Customer("cus-409", "Nadia Okafor", "premium"),
    Customer("cus-410", "Robin Park", "standard"),
]
TRANSACTIONS = [
    Transaction("txn-100", 42.50, "USD", "settled", 8),
    Transaction("txn-200", 275.00, "USD", "settled", 24),
    Transaction("txn-300", 89.00, "USD", "settled", 91),
    Transaction("txn-400", 18.00, "USD", "pending", 5),
    Transaction("txn-401", 64.20, "USD", "settled", 12),
    Transaction("txn-402", 128.00, "USD", "settled", 18),
    Transaction("txn-403", 58.40, "USD", "settled", 9),
    Transaction("txn-404", 19.99, "USD", "settled", 4),
    Transaction("txn-405", 410.00, "USD", "settled", 33),
    Transaction("txn-406", 74.50, "USD", "pending", 18),
    Transaction("txn-407", 92.00, "USD", "settled", 84),
    Transaction("txn-408", 650.00, "USD", "settled", 28),
    Transaction("txn-409", 36.75, "USD", "settled", 7),
    Transaction("txn-410", 18.00, "USD", "settled", 11),
]
CONVERSATIONS = [
    Conversation("conv-100", ["I would like a refund for order OR-8841.", "The item arrived unused and I have the order email."]),
    Conversation("conv-200", ["Please refund the full amount for order OR-1940.", "The device arrived damaged and the replacement window is closing."]),
    Conversation("conv-300", ["I do not recognize this transaction.", "Please freeze any further activity while this is investigated."]),
    Conversation("conv-400", ["Can you help?"]),
    Conversation("conv-401", ["I was charged twice for order OR-7021.", "Both charges show as settled on my bank statement."]),
    Conversation("conv-402", ["Your team promised my refund last week.", "I still cannot see the credit for order OR-3340."]),
    Conversation("conv-403", ["Can you make an exception to the return window?", "The order was delayed while I was travelling."]),
    Conversation("conv-404", ["What is the status of payment txn-404?", "I only need to know whether it completed."]),
    Conversation("conv-405", ["Please refund this business purchase for 410 dollars.", "The customer success manager approved it in a call."]),
    Conversation("conv-406", ["The payment is still pending after three days.", "Can you confirm whether I should retry?"]),
    Conversation("conv-407", ["I do not recognize this card payment.", "I have checked with my team and nobody placed it."]),
    Conversation("conv-408", ["The dashboard says captured but the ledger says reversed.", "Please do not issue another refund until this is reconciled."]),
    Conversation("conv-409", ["Please confirm the delivery charge on my invoice.", "I need the line item for my expense report."]),
    Conversation("conv-410", ["Please close the account and remove the saved payment method.", "I confirm I want this action completed today."]),
]
POLICIES = [Policy("pol-std")]
CASES = [
    Case("case-100", "Small settled refund", "cus-100", "conv-100", "txn-100", "pol-std", "refund-standard", "normal", "open", owner="Billing queue"),
    Case("case-200", "Large damaged-order refund", "cus-200", "conv-200", "txn-200", "pol-std", "refund-approval", "high", "open", owner="Billing queue"),
    Case("case-300", "Unrecognized transaction", "cus-300", "conv-300", "txn-300", "pol-std", "fraud-handoff", "urgent", "open", owner="Fraud review"),
    Case("case-400", "Vague support request", "cus-100", "conv-400", "txn-400", "pol-std", "missing-context", "normal", "open"),
    Case("case-401", "Possible duplicate charge", "cus-401", "conv-401", "txn-401", "pol-std", "duplicate-charge", "high", "open"),
    Case("case-402", "Refund promise not visible", "cus-402", "conv-402", "txn-402", "pol-std", "refund-missing", "high", "open"),
    Case("case-403", "Return window exception", "cus-403", "conv-403", "txn-403", "pol-std", "policy-exception", "medium", "open"),
    Case("case-404", "Routine payment status", "cus-404", "conv-404", "txn-404", "pol-std", "status-lookup", "low", "open"),
    Case("case-405", "Business refund approval", "cus-405", "conv-405", "txn-405", "pol-std", "account-action", "high", "open"),
    Case("case-406", "Payment pending review", "cus-406", "conv-406", "txn-406", "pol-std", "status-lookup", "medium", "open"),
    Case("case-407", "Card payment concern", "cus-407", "conv-407", "txn-407", "pol-std", "fraud-handoff", "urgent", "open"),
    Case("case-408", "Ledger and dashboard conflict", "cus-408", "conv-408", "txn-408", "pol-std", "conflicting-records", "urgent", "open"),
    Case("case-409", "Invoice line-item question", "cus-409", "conv-409", "txn-409", "pol-std", "status-lookup", "low", "open"),
    Case("case-410", "Account closure request", "cus-410", "conv-410", "txn-410", "pol-std", "account-action", "high", "open"),
]
